packages:
  - '.'
overrides:
  '@opentelemetry/core@<2.8.0': ^2.8.0
  '@sanity/uuid': 3.0.3
  js-yaml@<3.14.2: ^3.14.2
  js-yaml@<=4.1.1: ^4.1.2
  postcss: 8.5.15
  sanity: 5.29.0
  uuid@<11.1.1: ^11.1.1
allowBuilds:
  '@sentry/cli': false
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - js-yaml@3.14.2
  - uuid@11.1.1
  - js-yaml@4.1.2
  - '@opentelemetry/core@2.8.0'
